spring:
  application:
    name: wtf2

  datasource:
    url: jdbc:h2:tcp://localhost/D:/h2/wtf2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8080
